export interface Language {
  flag: string;
  language: string;
  code: string;
}

export const english = { flag: '🇬🇧', language: 'English', code: 'en' };

export const languages: Language[] = [
  { flag: '🇺🇸', language: 'English', code: 'en' },
  { flag: '🇪🇸', language: 'Spanish', code: 'es' },
  { flag: '🇩🇪', language: 'German', code: 'de' },
  { flag: '🇫🇷', language: 'French', code: 'fr' },
  { flag: '🇮🇳', language: 'Hindi', code: 'hi' },
  { flag: '🇳🇱', language: 'Dutch', code: 'nl' },
  { flag: '🇿🇦', language: 'Afrikaans', code: 'af' },
  { flag: '🇪🇹', language: 'Amharic', code: 'am' },
  { flag: '🇸🇦', language: 'Arabic', code: 'ar' },
  { flag: '🇮🇳', language: 'Assamese', code: 'as' },
  { flag: '🇦🇿', language: 'Azerbaijani', code: 'az' },
  { flag: '🇷🇺', language: 'Bashkir', code: 'ba' },
  { flag: '🇧🇾', language: 'Belarusian', code: 'be' },
  { flag: '🇧🇬', language: 'Bulgarian', code: 'bg' },
  { flag: '🇧🇩', language: 'Bengali', code: 'bn' },
  { flag: '🏳️', language: 'Tibetan', code: 'bo' },
  { flag: '🇫🇷', language: 'Breton', code: 'br' },
  { flag: '🇧🇦', language: 'Bosnian', code: 'bs' },
  { flag: '🇪🇸', language: 'Catalan', code: 'ca' },
  { flag: '🇨🇿', language: 'Czech', code: 'cs' },
  { flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', language: 'Welsh', code: 'cy' },
  { flag: '🇩🇰', language: 'Danish', code: 'da' },
  { flag: '🇬🇷', language: 'Greek', code: 'el' },
  { flag: '🇪🇪', language: 'Estonian', code: 'et' },
  { flag: '🇪🇺', language: 'Basque', code: 'eu' },
  { flag: '🇮🇷', language: 'Persian', code: 'fa' },
  { flag: '🇫🇮', language: 'Finnish', code: 'fi' },
  { flag: '🇫🇴', language: 'Faroese', code: 'fo' },
  { flag: '🇪🇸', language: 'Galician', code: 'gl' },
  { flag: '🇮🇳', language: 'Gujarati', code: 'gu' },
  { flag: '🇳🇬', language: 'Hausa', code: 'ha' },
  { flag: '🇺🇸', language: 'Hawaiian', code: 'haw' },
  { flag: '🇮🇱', language: 'Hebrew', code: 'he' },
  { flag: '🇭🇷', language: 'Croatian', code: 'hr' },
  { flag: '🇭🇹', language: 'Haitian Creole', code: 'ht' },
  { flag: '🇭🇺', language: 'Hungarian', code: 'hu' },
  { flag: '🇦🇲', language: 'Armenian', code: 'hy' },
  { flag: '🇮🇩', language: 'Indonesian', code: 'id' },
  { flag: '🇮🇸', language: 'Icelandic', code: 'is' },
  { flag: '🇮🇹', language: 'Italian', code: 'it' },
  { flag: '🇯🇵', language: 'Japanese', code: 'ja' },
  { flag: '🇮🇩', language: 'Javanese', code: 'jw' },
  { flag: '🇬🇪', language: 'Georgian', code: 'ka' },
  { flag: '🇰🇿', language: 'Kazakh', code: 'kk' },
  { flag: '🇰🇭', language: 'Khmer', code: 'km' },
  { flag: '🇮🇳', language: 'Kannada', code: 'kn' },
  { flag: '🇰🇷', language: 'Korean', code: 'ko' },
  { flag: '🇻🇦', language: 'Latin', code: 'la' },
  { flag: '🇱🇺', language: 'Luxembourgish', code: 'lb' },
  { flag: '🇨🇩', language: 'Lingala', code: 'ln' },
  { flag: '🇱🇦', language: 'Lao', code: 'lo' },
  { flag: '🇱🇹', language: 'Lithuanian', code: 'lt' },
  { flag: '🇱🇻', language: 'Latvian', code: 'lv' },
  { flag: '🇲🇬', language: 'Malagasy', code: 'mg' },
  { flag: '🇳🇿', language: 'Maori', code: 'mi' },
  { flag: '🇲🇰', language: 'Macedonian', code: 'mk' },
  { flag: '🇮🇳', language: 'Malayalam', code: 'ml' },
  { flag: '🇲🇳', language: 'Mongolian', code: 'mn' },
  { flag: '🇮🇳', language: 'Marathi', code: 'mr' },
  { flag: '🇲🇾', language: 'Malay', code: 'ms' },
  { flag: '🇲🇹', language: 'Maltese', code: 'mt' },
  { flag: '🇲🇲', language: 'Burmese', code: 'my' },
  { flag: '🇳🇵', language: 'Nepali', code: 'ne' },
  { flag: '🇳🇴', language: 'Norwegian Nynorsk', code: 'nn' },
  { flag: '🇳🇴', language: 'Norwegian', code: 'no' },
  { flag: '🇫🇷', language: 'Occitan', code: 'oc' },
  { flag: '🇮🇳', language: 'Punjabi', code: 'pa' },
  { flag: '🇵🇱', language: 'Polish', code: 'pl' },
  { flag: '🇦🇫', language: 'Pashto', code: 'ps' },
  { flag: '🇵🇹', language: 'Portuguese', code: 'pt' },
  { flag: '🇷🇴', language: 'Romanian', code: 'ro' },
  { flag: '🇷🇺', language: 'Russian', code: 'ru' },
  { flag: '🇮🇳', language: 'Sanskrit', code: 'sa' },
  { flag: '🇵🇰', language: 'Sindhi', code: 'sd' },
  { flag: '🇱🇰', language: 'Sinhala', code: 'si' },
  { flag: '🇸🇰', language: 'Slovak', code: 'sk' },
  { flag: '🇸🇮', language: 'Slovenian', code: 'sl' },
  { flag: '🇿🇼', language: 'Shona', code: 'sn' },
  { flag: '🇸🇴', language: 'Somali', code: 'so' },
  { flag: '🇦🇱', language: 'Albanian', code: 'sq' },
  { flag: '🇷🇸', language: 'Serbian', code: 'sr' },
  { flag: '🇮🇩', language: 'Sundanese', code: 'su' },
  { flag: '🇸🇪', language: 'Swedish', code: 'sv' },
  { flag: '🇰🇪', language: 'Swahili', code: 'sw' },
  { flag: '🇮🇳', language: 'Tamil', code: 'ta' },
  { flag: '🇮🇳', language: 'Telugu', code: 'te' },
  { flag: '🇹🇯', language: 'Tajik', code: 'tg' },
  { flag: '🇹🇭', language: 'Thai', code: 'th' },
  { flag: '🇹🇲', language: 'Turkmen', code: 'tk' },
  { flag: '🇵🇭', language: 'Tagalog', code: 'tl' },
  { flag: '🇹🇷', language: 'Turkish', code: 'tr' },
  { flag: '🇷🇺', language: 'Tatar', code: 'tt' },
  { flag: '🇺🇦', language: 'Ukrainian', code: 'uk' },
  { flag: '🇵🇰', language: 'Urdu', code: 'ur' },
  { flag: '🇺🇿', language: 'Uzbek', code: 'uz' },
  { flag: '🇻🇳', language: 'Vietnamese', code: 'vi' },
  { flag: '🇮🇱', language: 'Yiddish', code: 'yi' },
  { flag: '🇳🇬', language: 'Yoruba', code: 'yo' },
  { flag: '🇭🇰', language: 'Cantonese', code: 'yue' },
  { flag: '🇨🇳', language: 'Chinese (Mandarin)', code: 'zh' },
];
